#!/bin/python3
import sys
import socket

from datetime import date

today = date.today()


def scan(port, target):

    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    result = s.connect_ex((target,port))

    if result == 0:
        print(f"port {port} is open.")

    s.close()


if len(sys.argv) == 2:
    if sys.argv[1] == "--help" or sys.argv[1] == "-h":
        print("Usage: port_scanner ... [IP ADDRESS]...")
        print("Example: port_scanner 172.21.173.182")
    else:
        print("Today's date is", today)
        print("-"*30)
        for p in range(0,65535):
            scan(p,sys.argv[1])
        print("-"*30)
else:
    print("Please enter the target!")
    


